[project]
name = "rag-shared"
version = "0.1.0"
description = "Shared utilities for RAG platform"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
