name: CI - Fast Lint & Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    name: Python lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry virtualenvs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --with dev

      - name: Lint (Ruff + Black)
        run: |
          poetry run ruff check --fix .
          poetry run black --check .

      - name: Run tests
        run: poetry run pytest -q --disable-warnings

  frontend:
    name: Node lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint + Prettier)
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx
          npx prettier --check .

  precommit:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files --show-diff-on-failure

  smoke:
    name: Smoke tests
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run API smoke test
        run: |
          set -euo pipefail
          poetry run uvicorn coordinator.app.main:app --host 0.0.0.0 --port 8001 &
          coord_pid=$!
          COORDINATOR_BASE_URL=http://localhost:8001 poetry run uvicorn api.app.main:app --host 0.0.0.0 --port 8000 &
          api_pid=$!
          trap "kill $api_pid $coord_pid" EXIT
          sleep 5
          curl -fsS http://127.0.0.1:8000/healthz
          curl -fsS http://127.0.0.1:8001/healthz
          curl -fsS -X POST http://127.0.0.1:8000/dispatch \
            -H 'Content-Type: application/json' \
            -d '{"message":"ci-smoke"}'
